# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='common.proto',
  package='srv6pm',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0c\x63ommon.proto\x12\x06srv6pm\"\x1c\n\x08SRv6Path\x12\x10\n\x08segments\x18\x01 \x03(\t*\x88\x01\n\x12\x41uthenticationMode\x12#\n\x1f\x41UTHENTICATION_MODE_UNSPECIFIED\x10\x00\x12\'\n#AUTHENTICATION_MODE_UNAUTHENTICATED\x10\x01\x12$\n AUTHENTICATION_MODE_HMAC_SHA_256\x10\x02*i\n\x0fTimestampFormat\x12 \n\x1cTIMESTAMP_FORMAT_UNSPECIFIED\x10\x00\x12\x1a\n\x16TIMESTAMP_FORMAT_PTPv2\x10\x01\x12\x18\n\x14TIMESTAMP_FORMAT_NTP\x10\x02*\x90\x01\n\x0ePacketLossType\x12 \n\x1cPACKET_LOSS_TYPE_UNSPECIFIED\x10\x00\x12\x1f\n\x1bPACKET_LOSS_TYPE_ROUND_TRIP\x10\x01\x12\x1d\n\x19PACKET_LOSS_TYPE_NEAR_END\x10\x02\x12\x1c\n\x18PACKET_LOSS_TYPE_FAR_END\x10\x03*\xab\x01\n\x14\x44\x65layMeasurementMode\x12&\n\"DELAY_MEASUREMENT_MODE_UNSPECIFIED\x10\x00\x12\"\n\x1e\x44\x45LAY_MEASUREMENT_MODE_ONE_WAY\x10\x01\x12\"\n\x1e\x44\x45LAY_MEASUREMENT_MODE_TWO_WAY\x10\x02\x12#\n\x1f\x44\x45LAY_MEASUREMENT_MODE_LOOPBACK\x10\x03*\x89\x01\n\x14SessionReflectorMode\x12&\n\"SESSION_REFLECTOR_MODE_UNSPECIFIED\x10\x00\x12$\n SESSION_REFLECTOR_MODE_STATELESS\x10\x01\x12#\n\x1fSESSION_REFLECTOR_MODE_STATEFUL\x10\x02*\xf1\x02\n\nStatusCode\x12\x1b\n\x17STATUS_CODE_UNSPECIFIED\x10\x00\x12\x17\n\x13STATUS_CODE_SUCCESS\x10\x01\x12!\n\x1dSTATUS_CODE_SESSION_NOT_FOUND\x10\x02\x12\x1e\n\x1aSTATUS_CODE_SESSION_EXISTS\x10\x03\x12 \n\x1cSTATUS_CODE_INVALID_ARGUMENT\x10\x04\x12\x1f\n\x1bSTATUS_CODE_SESSION_RUNNING\x10\x05\x12#\n\x1fSTATUS_CODE_SESSION_NOT_RUNNING\x10\x06\x12\x1f\n\x1bSTATUS_CODE_NOT_INITIALIZED\x10\x07\x12#\n\x1fSTATUS_CODE_ALREADY_INITIALIZED\x10\x08\x12\x1c\n\x18STATUS_CODE_RESET_FAILED\x10\t\x12\x1e\n\x1aSTATUS_CODE_INTERNAL_ERROR\x10\nb\x06proto3'
)

_AUTHENTICATIONMODE = _descriptor.EnumDescriptor(
  name='AuthenticationMode',
  full_name='srv6pm.AuthenticationMode',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='AUTHENTICATION_MODE_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='AUTHENTICATION_MODE_UNAUTHENTICATED', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='AUTHENTICATION_MODE_HMAC_SHA_256', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=55,
  serialized_end=191,
)
_sym_db.RegisterEnumDescriptor(_AUTHENTICATIONMODE)

AuthenticationMode = enum_type_wrapper.EnumTypeWrapper(_AUTHENTICATIONMODE)
_TIMESTAMPFORMAT = _descriptor.EnumDescriptor(
  name='TimestampFormat',
  full_name='srv6pm.TimestampFormat',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TIMESTAMP_FORMAT_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TIMESTAMP_FORMAT_PTPv2', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TIMESTAMP_FORMAT_NTP', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=193,
  serialized_end=298,
)
_sym_db.RegisterEnumDescriptor(_TIMESTAMPFORMAT)

TimestampFormat = enum_type_wrapper.EnumTypeWrapper(_TIMESTAMPFORMAT)
_PACKETLOSSTYPE = _descriptor.EnumDescriptor(
  name='PacketLossType',
  full_name='srv6pm.PacketLossType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PACKET_LOSS_TYPE_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PACKET_LOSS_TYPE_ROUND_TRIP', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PACKET_LOSS_TYPE_NEAR_END', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PACKET_LOSS_TYPE_FAR_END', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=301,
  serialized_end=445,
)
_sym_db.RegisterEnumDescriptor(_PACKETLOSSTYPE)

PacketLossType = enum_type_wrapper.EnumTypeWrapper(_PACKETLOSSTYPE)
_DELAYMEASUREMENTMODE = _descriptor.EnumDescriptor(
  name='DelayMeasurementMode',
  full_name='srv6pm.DelayMeasurementMode',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DELAY_MEASUREMENT_MODE_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DELAY_MEASUREMENT_MODE_ONE_WAY', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DELAY_MEASUREMENT_MODE_TWO_WAY', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DELAY_MEASUREMENT_MODE_LOOPBACK', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=448,
  serialized_end=619,
)
_sym_db.RegisterEnumDescriptor(_DELAYMEASUREMENTMODE)

DelayMeasurementMode = enum_type_wrapper.EnumTypeWrapper(_DELAYMEASUREMENTMODE)
_SESSIONREFLECTORMODE = _descriptor.EnumDescriptor(
  name='SessionReflectorMode',
  full_name='srv6pm.SessionReflectorMode',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SESSION_REFLECTOR_MODE_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SESSION_REFLECTOR_MODE_STATELESS', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SESSION_REFLECTOR_MODE_STATEFUL', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=622,
  serialized_end=759,
)
_sym_db.RegisterEnumDescriptor(_SESSIONREFLECTORMODE)

SessionReflectorMode = enum_type_wrapper.EnumTypeWrapper(_SESSIONREFLECTORMODE)
_STATUSCODE = _descriptor.EnumDescriptor(
  name='StatusCode',
  full_name='srv6pm.StatusCode',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STATUS_CODE_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STATUS_CODE_SUCCESS', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STATUS_CODE_SESSION_NOT_FOUND', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STATUS_CODE_SESSION_EXISTS', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STATUS_CODE_INVALID_ARGUMENT', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STATUS_CODE_SESSION_RUNNING', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STATUS_CODE_SESSION_NOT_RUNNING', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STATUS_CODE_NOT_INITIALIZED', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STATUS_CODE_ALREADY_INITIALIZED', index=8, number=8,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STATUS_CODE_RESET_FAILED', index=9, number=9,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STATUS_CODE_INTERNAL_ERROR', index=10, number=10,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=762,
  serialized_end=1131,
)
_sym_db.RegisterEnumDescriptor(_STATUSCODE)

StatusCode = enum_type_wrapper.EnumTypeWrapper(_STATUSCODE)
AUTHENTICATION_MODE_UNSPECIFIED = 0
AUTHENTICATION_MODE_UNAUTHENTICATED = 1
AUTHENTICATION_MODE_HMAC_SHA_256 = 2
TIMESTAMP_FORMAT_UNSPECIFIED = 0
TIMESTAMP_FORMAT_PTPv2 = 1
TIMESTAMP_FORMAT_NTP = 2
PACKET_LOSS_TYPE_UNSPECIFIED = 0
PACKET_LOSS_TYPE_ROUND_TRIP = 1
PACKET_LOSS_TYPE_NEAR_END = 2
PACKET_LOSS_TYPE_FAR_END = 3
DELAY_MEASUREMENT_MODE_UNSPECIFIED = 0
DELAY_MEASUREMENT_MODE_ONE_WAY = 1
DELAY_MEASUREMENT_MODE_TWO_WAY = 2
DELAY_MEASUREMENT_MODE_LOOPBACK = 3
SESSION_REFLECTOR_MODE_UNSPECIFIED = 0
SESSION_REFLECTOR_MODE_STATELESS = 1
SESSION_REFLECTOR_MODE_STATEFUL = 2
STATUS_CODE_UNSPECIFIED = 0
STATUS_CODE_SUCCESS = 1
STATUS_CODE_SESSION_NOT_FOUND = 2
STATUS_CODE_SESSION_EXISTS = 3
STATUS_CODE_INVALID_ARGUMENT = 4
STATUS_CODE_SESSION_RUNNING = 5
STATUS_CODE_SESSION_NOT_RUNNING = 6
STATUS_CODE_NOT_INITIALIZED = 7
STATUS_CODE_ALREADY_INITIALIZED = 8
STATUS_CODE_RESET_FAILED = 9
STATUS_CODE_INTERNAL_ERROR = 10



_SRV6PATH = _descriptor.Descriptor(
  name='SRv6Path',
  full_name='srv6pm.SRv6Path',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='segments', full_name='srv6pm.SRv6Path.segments', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=52,
)

DESCRIPTOR.message_types_by_name['SRv6Path'] = _SRV6PATH
DESCRIPTOR.enum_types_by_name['AuthenticationMode'] = _AUTHENTICATIONMODE
DESCRIPTOR.enum_types_by_name['TimestampFormat'] = _TIMESTAMPFORMAT
DESCRIPTOR.enum_types_by_name['PacketLossType'] = _PACKETLOSSTYPE
DESCRIPTOR.enum_types_by_name['DelayMeasurementMode'] = _DELAYMEASUREMENTMODE
DESCRIPTOR.enum_types_by_name['SessionReflectorMode'] = _SESSIONREFLECTORMODE
DESCRIPTOR.enum_types_by_name['StatusCode'] = _STATUSCODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SRv6Path = _reflection.GeneratedProtocolMessageType('SRv6Path', (_message.Message,), {
  'DESCRIPTOR' : _SRV6PATH,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:srv6pm.SRv6Path)
  })
_sym_db.RegisterMessage(SRv6Path)


# @@protoc_insertion_point(module_scope)
