# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import stamp_sender_pb2 as stamp__sender__pb2


class STAMPSessionSenderServiceStub(object):
    """STAMPSessionSenderService provides RPCs used to control a STAMP Session
    Sender
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Init = channel.unary_unary(
                '/srv6pm.STAMPSessionSenderService/Init',
                request_serializer=stamp__sender__pb2.InitStampSenderRequest.SerializeToString,
                response_deserializer=stamp__sender__pb2.InitStampSenderReply.FromString,
                )
        self.Reset = channel.unary_unary(
                '/srv6pm.STAMPSessionSenderService/Reset',
                request_serializer=stamp__sender__pb2.ResetStampSenderRequest.SerializeToString,
                response_deserializer=stamp__sender__pb2.ResetStampSenderReply.FromString,
                )
        self.CreateStampSession = channel.unary_unary(
                '/srv6pm.STAMPSessionSenderService/CreateStampSession',
                request_serializer=stamp__sender__pb2.CreateStampSenderSessionRequest.SerializeToString,
                response_deserializer=stamp__sender__pb2.CreateStampSenderSessionReply.FromString,
                )
        self.StartStampSession = channel.unary_unary(
                '/srv6pm.STAMPSessionSenderService/StartStampSession',
                request_serializer=stamp__sender__pb2.StartStampSenderSessionRequest.SerializeToString,
                response_deserializer=stamp__sender__pb2.StartStampSenderSessionReply.FromString,
                )
        self.StopStampSession = channel.unary_unary(
                '/srv6pm.STAMPSessionSenderService/StopStampSession',
                request_serializer=stamp__sender__pb2.StopStampSenderSessionRequest.SerializeToString,
                response_deserializer=stamp__sender__pb2.StopStampSenderSessionReply.FromString,
                )
        self.GetStampSessionResults = channel.unary_unary(
                '/srv6pm.STAMPSessionSenderService/GetStampSessionResults',
                request_serializer=stamp__sender__pb2.GetStampSessionResultsRequest.SerializeToString,
                response_deserializer=stamp__sender__pb2.StampResults.FromString,
                )
        self.DestroyStampSession = channel.unary_unary(
                '/srv6pm.STAMPSessionSenderService/DestroyStampSession',
                request_serializer=stamp__sender__pb2.DestroyStampSenderSessionRequest.SerializeToString,
                response_deserializer=stamp__sender__pb2.DestroyStampSenderSessionReply.FromString,
                )


class STAMPSessionSenderServiceServicer(object):
    """STAMPSessionSenderService provides RPCs used to control a STAMP Session
    Sender
    """

    def Init(self, request, context):
        """Init: RPC used to initialize the Session Sender
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reset(self, request, context):
        """Reset: RPC used to initialize the Session Sender
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateStampSession(self, request, context):
        """CreateStampSession: RPC used to create a STAMP Session
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartStampSession(self, request, context):
        """StartStampSession: RPC used to start a STAMP Session
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopStampSession(self, request, context):
        """StopStampSession: RPC used to stop a STAMP Session
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStampSessionResults(self, request, context):
        """GetStampSessionResults: Return the results for a given STAMP Session
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DestroyStampSession(self, request, context):
        """DestroyStampSession: RPC used to destroy an existing STAMP Session
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_STAMPSessionSenderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Init': grpc.unary_unary_rpc_method_handler(
                    servicer.Init,
                    request_deserializer=stamp__sender__pb2.InitStampSenderRequest.FromString,
                    response_serializer=stamp__sender__pb2.InitStampSenderReply.SerializeToString,
            ),
            'Reset': grpc.unary_unary_rpc_method_handler(
                    servicer.Reset,
                    request_deserializer=stamp__sender__pb2.ResetStampSenderRequest.FromString,
                    response_serializer=stamp__sender__pb2.ResetStampSenderReply.SerializeToString,
            ),
            'CreateStampSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateStampSession,
                    request_deserializer=stamp__sender__pb2.CreateStampSenderSessionRequest.FromString,
                    response_serializer=stamp__sender__pb2.CreateStampSenderSessionReply.SerializeToString,
            ),
            'StartStampSession': grpc.unary_unary_rpc_method_handler(
                    servicer.StartStampSession,
                    request_deserializer=stamp__sender__pb2.StartStampSenderSessionRequest.FromString,
                    response_serializer=stamp__sender__pb2.StartStampSenderSessionReply.SerializeToString,
            ),
            'StopStampSession': grpc.unary_unary_rpc_method_handler(
                    servicer.StopStampSession,
                    request_deserializer=stamp__sender__pb2.StopStampSenderSessionRequest.FromString,
                    response_serializer=stamp__sender__pb2.StopStampSenderSessionReply.SerializeToString,
            ),
            'GetStampSessionResults': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStampSessionResults,
                    request_deserializer=stamp__sender__pb2.GetStampSessionResultsRequest.FromString,
                    response_serializer=stamp__sender__pb2.StampResults.SerializeToString,
            ),
            'DestroyStampSession': grpc.unary_unary_rpc_method_handler(
                    servicer.DestroyStampSession,
                    request_deserializer=stamp__sender__pb2.DestroyStampSenderSessionRequest.FromString,
                    response_serializer=stamp__sender__pb2.DestroyStampSenderSessionReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'srv6pm.STAMPSessionSenderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class STAMPSessionSenderService(object):
    """STAMPSessionSenderService provides RPCs used to control a STAMP Session
    Sender
    """

    @staticmethod
    def Init(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/srv6pm.STAMPSessionSenderService/Init',
            stamp__sender__pb2.InitStampSenderRequest.SerializeToString,
            stamp__sender__pb2.InitStampSenderReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/srv6pm.STAMPSessionSenderService/Reset',
            stamp__sender__pb2.ResetStampSenderRequest.SerializeToString,
            stamp__sender__pb2.ResetStampSenderReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateStampSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/srv6pm.STAMPSessionSenderService/CreateStampSession',
            stamp__sender__pb2.CreateStampSenderSessionRequest.SerializeToString,
            stamp__sender__pb2.CreateStampSenderSessionReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StartStampSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/srv6pm.STAMPSessionSenderService/StartStampSession',
            stamp__sender__pb2.StartStampSenderSessionRequest.SerializeToString,
            stamp__sender__pb2.StartStampSenderSessionReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StopStampSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/srv6pm.STAMPSessionSenderService/StopStampSession',
            stamp__sender__pb2.StopStampSenderSessionRequest.SerializeToString,
            stamp__sender__pb2.StopStampSenderSessionReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetStampSessionResults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/srv6pm.STAMPSessionSenderService/GetStampSessionResults',
            stamp__sender__pb2.GetStampSessionResultsRequest.SerializeToString,
            stamp__sender__pb2.StampResults.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DestroyStampSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/srv6pm.STAMPSessionSenderService/DestroyStampSession',
            stamp__sender__pb2.DestroyStampSenderSessionRequest.SerializeToString,
            stamp__sender__pb2.DestroyStampSenderSessionReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
